# Generated by Django 5.0.3 on 2024-04-04 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.category'),
        ),
    ]
