# Generated by Django 5.0.3 on 2024-04-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_productos_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
