# Generated by Django 5.0.4 on 2024-04-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_productos_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
